import { findRestaurant, norm } from '../../../../shared/restaurants';

/** Snapshot of every chain exposed by healthyfastfood.org's public restaurant directory. */
export const HFF_RESTAURANTS = [
  ['Salsarita\'s Fresh Mexican Grill', 'salsaritas-fresh-mexican-grill'],
  ['7-Eleven', '7-eleven'],
  ['Caseys', 'caseys'],
  ['Kwik Trip', 'kwik-trip'],
  ['Sheetz', 'sheetz'],
  ['Wawa', 'wawa'],
  ['Taco Time', 'taco-time'],
  ['Fuddruckers', 'fuddruckers'],
  ['Cook Out', 'cook-out'],
  ['Quiznos', 'quiznos'],
  ['Pita Pit', 'pita-pit'],
  ['Freebirds', 'freebirds'],
  ['Saladworks', 'saladworks'],
  ['Bibibop', 'bibibop'],
  ['Baja Fresh', 'baja-fresh'],
  ['Pinkberry', 'pinkberry'],
  ['Manchu Wok', 'manchu-wok'],
  ['Freshii', 'freshii'],
  ['Chicken Express', 'chicken-express'],
  ['PDQ', 'pdq'],
  ['Costco Food Court', 'costco'],
  ['Mission BBQ', 'mission-bbq'],
  ['Blimpie', 'blimpie'],
  ['Perry\'s Steakhouse & Grille', 'perrys-steakhouse-grille'],
  ['Pappasito\'s Cantina', 'pappasitos-cantina'],
  ['Which Wich?', 'which-wich'],
  ['Bruegger\'s Bagels', 'brueggers-bagels'],
  ['Tijuana Flats', 'tijuana-flats'],
  ['La Madeleine', 'la-madeleine'],
  ['BurgerFi', 'burgerfi'],
  ['Waba Grill', 'waba-grill'],
  ['Costa Vida', 'costa-vida-fresh-mexican-grill'],
  ['Zoë\'s Kitchen', 'zoes-kitchen'],
  ['Au Bon Pain', 'au-bon-pain'],
  ['Sbarro', 'sbarro'],
  ['Cava', 'cava'],
  ['Pei Wei', 'pei-wei'],
  ['Rubio\'s Coastal Grill', 'rubios-coastal-grill'],
  ['Newk\'s Eatery', 'newks-eatery'],
  ['Donatos Pizza', 'donatos-pizza'],
  ['Cinnabon', 'cinnabon'],
  ['Corner Bakery', 'corner-bakery'],
  ['Smashburger', 'smashburger'],
  ['Chicken Salad Chick', 'chicken-salad-chick'],
  ['Penn Station East Coast Subs', 'penn-station-east-coast-subs'],
  ['Taco Cabana', 'taco-cabana'],
  ['Godfather\'s Pizza', 'godfathers-pizza'],
  ['Pizza Ranch', 'pizza-ranch'],
  ['On the Border Mexican Grill & Cantina', 'on-the-border-mexican-grill-cantina'],
  ['Ruby Tuesday', 'ruby-tuesday'],
  ['Fazoli\'s', 'fazolis'],
  ['Famous Dave\'s', 'famous-daves'],
  ['Cafe Rio Mexican Grill', 'cafe-rio-mexican-grill'],
  ['Krystal Company', 'krystal-company'],
  ['Caribou Coffee', 'caribou-coffee'],
  ['Schlotzsky\'s', 'schlotzskys'],
  ['Long John Silver\'s', 'long-john-silvers'],
  ['Sweetgreen', 'sweetgreen'],
  ['Blaze Pizza', 'blaze-pizza'],
  ['Nothing Bundt Cakes', 'nothing-bundt-cakes'],
  ['Wienerschnitzel', 'wienerschnitzel'],
  ['O\'Charley\'s', 'ocharleys'],
  ['Jet\'s Pizza', 'jets-pizza'],
  ['Chuy\'s', 'chuys'],
  ['Mellow Mushroom', 'mellow-mushroom'],
  ['Taco John\'s', 'taco-johns'],
  ['Boston Market', 'boston-market'],
  ['Cold Stone Creamery', 'cold-stone-creamery'],
  ['Pollo Tropical', 'pollo-tropical'],
  ['Potbelly Sandwich Shop', 'potbelly-sandwich-shop'],
  ['Hungry Howie\'s Pizza', 'hungry-howies-pizza'],
  ['California Pizza Kitchen', 'california-pizza-kitchen'],
  ['Perkins Restaurant & Bakery', 'perkins-restaurant-bakery'],
  ['Jamba Juice', 'jamba-juice'],
  ['Jason\'s Deli', 'jasons-deli'],
  ['Portillo\'s', 'portillos'],
  ['Noodles & Company', 'noodles-company'],
  ['Captain D\'s Seafood Kitchen', 'captain-ds-seafood-kitchen'],
  ['Auntie Anne\'s', 'auntie-annes'],
  ['The Habit Burger Grill', 'habit-burger-grill'],
  ['Yard House', 'yard-house'],
  ['MOD Pizza', 'mod-pizza'],
  ['Tim Hortons', 'tim-hortons'],
  ['Smoothie King', 'smoothie-king'],
  ['White Castle', 'white-castle'],
  ['Checkers', 'checkers'],
  ['Moe\'s Southwest Grill', 'moes-southwest-grill'],
  ['Baskin-Robbins', 'baskin-robbins'],
  ['Carrabba\'s Italian Grill', 'carrabbas-italian-grill'],
  ['Bob Evans', 'bob-evans'],
  ['First Watch', 'first-watch'],
  ['Freddy\'s Frozen Custard & Steakburgers', 'freddys-frozen-custard-steakburgers'],
  ['Shake Shack', 'shake-shack'],
  ['Church\'s Chicken', 'churchs-chicken'],
  ['TGI Fridays', 'tgi-fridays'],
  ['Papa Murphy\'s Pizza', 'papa-murphys-pizza'],
  ['Krispy Kreme', 'krispy-kreme'],
  ['Steak \'n Shake', 'steak-n-shake'],
  ['Hooters', 'hooters'],
  ['McAlister\'s Deli', 'mcalisters-deli'],
  ['Qdoba Mexican Eats', 'qdoba-mexican-eats'],
  ['Marco\'s Pizza', 'marcos-pizza'],
  ['Del Taco', 'del-taco'],
  ['P.F. Chang\'s', 'pf-changs'],
  ['Tropical Smoothie Cafe', 'tropical-smoothie-cafe'],
  ['El Pollo Loco', 'el-pollo-loco'],
  ['Firehouse Subs', 'firehouse-subs'],
  ['BJ\'s Restaurant & Brewhouse', 'bjs-restaurant-brewhouse'],
  ['Golden Corral', 'golden-corral'],
  ['Waffle House', 'waffle-house'],
  ['Red Robin', 'red-robin'],
  ['Bojangles', 'bojangles'],
  ['Carl\'s Jr.', 'carls-jr'],
  ['In-N-Out Burger', 'in-n-out-burger'],
  ['Hardee\'s', 'hardees'],
  ['Five Guys', 'five-guys'],
  ['Wingstop', 'wingstop'],
  ['Jersey Mike\'s Subs', 'jersey-mikes-subs'],
  ['LongHorn Steakhouse', 'longhorn-steakhouse'],
  ['Zaxby\'s', 'zaxbys'],
  ['The Cheesecake Factory', 'cheesecake-factory'],
  ['Jimmy John\'s', 'jimmy-johns'],
  ['Red Lobster', 'red-lobster'],
  ['Raising Cane\'s Chicken Fingers', 'raising-canes-chicken-fingers'],
  ['Cracker Barrel', 'cracker-barrel'],
  ['Denny\'s', 'dennys'],
  ['Culver\'s', 'culvers'],
  ['Outback Steakhouse', 'outback-steakhouse'],
  ['IHOP', 'ihop'],
  ['Whataburger', 'whataburger'],
  ['Chili\'s Grill & Bar', 'chilis-grill-bar'],
  ['Papa John\'s', 'papa-johns'],
  ['Texas Roadhouse', 'texas-roadhouse'],
  ['Buffalo Wild Wings', 'buffalo-wild-wings'],
  ['Jack in the Box', 'jack-in-the-box'],
  ['Applebee\'s', 'applebees'],
  ['Olive Garden', 'olive-garden'],
  ['Little Caesars', 'little-caesars'],
  ['Arby\'s', 'arbys'],
  ['Dairy Queen', 'dairy-queen'],
  ['Panda Express', 'panda-express'],
  ['Popeyes', 'popeyes'],
  ['KFC', 'kfc'],
  ['Pizza Hut', 'pizza-hut'],
  ['Panera Bread', 'panera-bread'],
  ['Sonic Drive-In', 'sonic-drive-in'],
  ['Chipotle Mexican Grill', 'chipotle-mexican-grill'],
  ['Domino\'s', 'dominos-pizza'],
  ['Subway', 'subway'],
  ['Burger King', 'burger-king'],
  ['Dunkin\' Donuts', 'dunkin-donuts'],
  ['Wendy\'s', 'wendys'],
  ['Taco Bell', 'taco-bell'],
  ['Chick-fil-A', 'chick-fil-a'],
  ['Starbucks', 'starbucks'],
  ['McDonald\'s', 'mcdonalds'],
] as const;

const EXTRA_ALIASES: Record<string, string[]> = {
  arbys: ['arbys'],
  applebees: ['applebees'],
  caseys: ['caseys'],
  culvers: ['culvers'],
  dennys: ['dennys'],
  'dominos-pizza': ['dominos'],
  'freddys-frozen-custard-steakburgers': ['freddys', 'freddy s'],
  'jersey-mikes-subs': ['jersey mikes'],
  'raising-canes-chicken-fingers': ['raising canes', 'canes'],
  'mcdonalds': ['mcdonalds'],
  'ocharleys': ['ocharleys'],
  'papa-johns': ['papa johns'],
  'portillos': ['portillos'],
  'schlotzskys': ['schlotzskys'],
  'wendys': ['wendys'],
};

const SHARED_SLUGS: Record<string, string> = {
  burger_king: 'burger-king',
  cava: 'cava',
  chick_fil_a: 'chick-fil-a',
  chipotle: 'chipotle-mexican-grill',
  culvers: 'culvers',
  dairy_queen: 'dairy-queen',
  dominos: 'dominos-pizza',
  five_guys: 'five-guys',
  in_n_out: 'in-n-out-burger',
  jersey_mikes: 'jersey-mikes-subs',
  mcdonalds: 'mcdonalds',
  olive_garden: 'olive-garden',
  panda_express: 'panda-express',
  panera: 'panera-bread',
  pizza_hut: 'pizza-hut',
  raising_canes: 'raising-canes-chicken-fingers',
  shake_shack: 'shake-shack',
  starbucks: 'starbucks',
  subway: 'subway',
  sweetgreen: 'sweetgreen',
  taco_bell: 'taco-bell',
  wendys: 'wendys',
};

export type HffRestaurant = { name: string; slug: string; alias: string };

export function findHffRestaurant(text: string): HffRestaurant | null {
  const shared = findRestaurant(text);
  if (shared) {
    const slug = SHARED_SLUGS[shared.restaurant.id];
    const match = HFF_RESTAURANTS.find(([, candidate]) => candidate === slug);
    if (match) return { name: match[0], slug: match[1], alias: shared.alias };
  }
  const haystack = ` ${norm(text)} `;
  let best: HffRestaurant | null = null;
  for (const [name, slug] of HFF_RESTAURANTS) {
    const aliases = [norm(name), norm(slug.replace(/-/g, ' ')), ...(EXTRA_ALIASES[slug] ?? [])];
    for (const alias of aliases) {
      if (haystack.includes(` ${alias} `) && (!best || alias.length > best.alias.length)) best = { name, slug, alias };
    }
  }
  return best;
}
